In [1]:
import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
from skimage.metrics import peak_signal_noise_ratio as psnr
from scipy.io import savemat
import pandas as pd

In [3]:
refdata = pd.read_csv("/workspace/algorithm/lijia/liyu/DNAMeth/data9000/met_file_celltype.csv")
reffilenames = refdata["title"]
celltype = refdata["SubType"]
marjortype = refdata["MajorType"]

In [10]:
import shutil
storedir = "/workspace/algorithm/lijia/liyu/DNAMeth/swavDNA/check_100kbratio_linear_lr0.1_nopretrianed/Fold0/cam/test_PredR/"
for i,ifile in enumerate(reffilenames):
    filename = "allc_"+ifile.split(".")[0]+".png"
    if not os.path.exists(os.path.join(storedir,marjortype[i],filename)):
        continue
    if not os.path.exists(os.path.join(storedir,"subtype")):
        os.makedirs(os.path.join(storedir,"subtype"))
    if not os.path.exists(os.path.join(storedir,"subtype",celltype[i])):
        os.makedirs(os.path.join(storedir,"subtype",celltype[i]))
    shutil.copy(os.path.join(storedir,marjortype[i],filename),os.path.join(storedir,"subtype",celltype[i]))


In [20]:
refdata = pd.read_csv("/workspace/algorithm/lijia/liyu/DNAMeth/data9000/windows100000_sort.bed",sep="\t",header=None)
refchrm = refdata[0]
refstart = refdata[1]
refend = refdata[2]

In [19]:
refdata

0       1       2
0                      chr1       0  100000
1                      chr1  100000  200000
2                      chr1  200000  300000
3                      chr1  300000  400000
4                      chr1  400000  500000
...                     ...     ...     ...
27343  chrY_JH584301_random  200000  259875
27344  chrY_JH584302_random       0  100000
27345  chrY_JH584302_random  100000  155838
27346  chrY_JH584303_random       0  100000
27347  chrY_JH584303_random  100000  158099

[27348 rows x 3 columns]

In [21]:
data = pd.read_csv("/workspace/algorithm/lijia/liyu/DNAMeth/data9000/100k_2969features.csv")
chrm = data["chrom"]
start_ = data["bin_start"] 
end_ = data["bin_end"] 

start_

0        3500000
1        3700000
2        4900000
3        5200000
4        5300000
          ...   
2964    57700000
2965    57800000
2966    57900000
2967    58500000
2968    60900000
Name: bin_start, Length: 2969, dtype: int64

In [24]:
import math
from PIL import Image
stor = ["chr1","chr2","chr3","chr4","chr5","chr6","chr7","chr8","chr9","chr10",\
        "chr11","chr12","chr13","chr14","chr15","chr16","chr17","chr18","chr19","chrM","chrX","chrY"]
arr = []
for i in range(len(refchrm)):
    if refchrm[i] in stor:
        index = np.where(start_==refstart[i])[0]
        
        if refstart[i] in start_:
            arr.append(1)
        else:
            arr.append(0)
img=np.asarray(arr,dtype="float64")
size_=math.isqrt(img.size)+1
print(size_)
regint = np.concatenate((img*255,np.zeros(size_*size_-img.size,)),axis=0).reshape((size_,size_))

res = Image.fromarray(regint.astype(np.uint8))
res.save("/workspace/algorithm/lijia/liyu/DNAMeth/data9000/ref_100kb.png")
            

[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[2439]
[0]
[2006 2703]
[1]
[1726]
[2704]
[897]
[]
[ 712 2440]
[2007 2157]
[1597 2441]
[1598 2442]
[ 516 1599]
[]
[ 898 2819]
[2]
[1443 1727 2008 2443]
[ 899 1444]
[3]
[   4 2570]
[   5  517 1445 1728 2571]
[2572]
[   6 1729 2444 2573 2705 2820]
[1730]
[ 900 1097 1600]
[ 901 1098 1601 2158]
[1602 2159 2821]
[2009]
[2160]
[902]
[1731]
[7]
[713]
[1099 2161]
[ 714 1305 1906 2162]
[1907 2163]
[1732 2164 2445 2706]
[   8 1733 2165]
[ 715 2166 2707]
[ 716 2010 2167 2574 2708]
[   9  717  903 2168]
[ 718 2169]
[  10 1908]
[2011 2170]
[2012 2171]
[1603]
[1100 1446 2013 2709]
[ 303 1101 2014]
[  11  304  904 1909 2172]
[  12 1102 1734 2173]
[2174 2301]
[  13 2175 2302 2575]
[1604 2176]
[ 719 1605 1735 1910 2177]
[ 518 1103]
[ 305 1736]
[1104 1447 1606 1737 2897]
[1105 1607 1738]
[1106 2015]
[1739 2016]
[ 905 1107 1448 1740 2017 2710]
[1741 2303 2711]
[1449 2304 2712]
[ 519 1108 2018]
[  14 2305 

In [25]:
print(sum(img))

22.0
